# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank='true', max_length=200)),
                ('password', models.CharField(blank='true', max_length=200)),
            ],
        ),
    ]
