# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='itemquantity',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AddField(
            model_name='items',
            name='itemprice',
            field=models.CharField(blank='true', max_length=200),
        ),
    ]
