# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170611_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemimage',
            new_name='image',
        ),
    ]
